### ISSUE TITLE
BUG: Gnosis EurE off-ramp bot fails to complete Transaction

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1060]
@fieldtheory123 attempted to test Gnosis bot today 12/11/2023 at around 2:00PM PST

1. Gnosis Bot EurE Contract deployed: https://gnosisscan.io/address/0xceb2b7113661dc89acc958ff8c51bdf4c4dc7de0#tokentxns
2. Test Transaction for Deposit and bridge to Gnosis chain appeared successful: https://etherscan.io/tx/0xc84ddbba903e1bbe2a91ecd69002ec33ac7124eacbc19b8d0b6428f8f0766b88
3. However, EurE: No swap completed. No Euro detected on the user account: https://gnosisscan.io/address/0xD0e08D653C3ead747865c3674FFa93ecDefDd045#tokentxns

We suspect that message was not relayed.

**Comment by webelf101** [comment]
The backend script is trying to send message but it hasn't been relayed. Please check queue to gnosis-main chain. @verabehr

**Comment by webelf101** [comment]
FYI @byte-bandit

**Comment by byte-bandit** [comment]
@webelf101 @taariq 

I assume this was on main net? 

I see a lot of messages going out to gnosis, they're all failing. 

Here's the extracted errors I was able to find, all coming from the smart contract:

### Error A

```
Reverted 0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000008536c697070616765000000000000000000000000000000000000000000000000
```

### Error B

`Reverted Slippage`

### Error C

`execution reverted: Slippage`

### Error D

`Reverted 0x536c697070616765`

---

If you parse the hex to ASCII, you'll see that all of these errors are connected to Slippage.

**Comment by byte-bandit** [comment]
You can look for errors like this by connecting to either the validator or the LCD, and checking the logs for error data connected to the target chain, like this:

`journalctl -u palomad --since "1 day ago" | grep "gnosis-main" | grep "error data"`

This will give you all the occurrences of messages that failed to relay when their error data is attached to the message. This is stored in HEX, so just pipe it through a HEX to ASCII converter (remove the leading 0x), and you have the plain error message.
