### ISSUE TITLE
Bug: Gnosis Offramp bug results in reverted transactions "out of gas"

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1158]
We first observed thsi on Jan 8 after fieldtheory's test https://discord.com/channels/987730379182051408/1065140873811218532/1194305892166946906. 

When testing again, we could reproduce this - details here https://www.notion.so/volumefi/Gnosis-offramp-bot-failures-ec6a4c6571634b85a8060b2c61cf7215?pvs=4

### Done when
Root cause for reverted out of gas transaction has  been identified and fixed

**Comment by webelf101** [comment]
@byte-bandit and I discussed increasing the gas limit from gas estimation. I think it will solve the "out of gas" issue.

**Comment by verabehr** [comment]
reverification blocked by https://github.com/VolumeFi/paloma/issues/1048

**Comment by byte-bandit** [comment]
@webelf101 @verabehr @taariq 

Is there another way we can address this issue, i.e. increasing the `gas-adjustment` setting for the target chain? 

Currently, the `go/ethereum` library takes care of gas estimations. We can extract the logic and run it ourselves, but it's not trivial and adds a lot of branching and complexity. 

I want to make sure that really is the right way forward before changing all the architecture & tests.

**Comment by webelf101** [comment]
gas-adjustment can't solve the issue. It is to increase gas price but our issue is gas estimation. I think increasing gas amount from gas estimation won't be so complex. @byte-bandit

**Comment by taariq** [comment]
@byte-bandit okay. We'll need to leave this for after Pigeon Feed and launch of the GRAIN token. Thank you @webelf101. we'll continue with the failures for now.

**Comment by byte-bandit** [comment]
> gas-adjustment can't solve the issue. It is to increase gas price but our issue is gas estimation. I think increasing gas amount from gas estimation won't be so complex.

Hmm, I see. 

So obviously adding as simple multiplication to the amount should not be a problem. The complexity arises from the fact that the entire code responsible for gas amount estimation is handled on a library layer, Paloma doesn't touch it. Meaning we don't even have access to this field to multiply it with a factor.

So there's two options:

- fork the library and make the needed changes ourselves. That would be my preferred solution, but we're already using two forks of this library, so we'd have to create and maintain two forks. Not ideal.
- extract this code from the library and do it ourselves. 

I have only focussed on option 2 until now, but it does introduce even more branching and complexity, which is why I wanted to avoid this. If there's no other way, we'll go for it.

**Comment by taariq** [comment]
Thanks for this @byte-bandit. Let's revisit this after Pigeon Feed.

**Comment by byte-bandit** [comment]
This was done with https://github.com/palomachain/pigeon/pull/358
