### ISSUE TITLE
BUG: Same message id was relayed twice

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1159]
observed a case where there are two different public access data for the same message ID.  This resulted in one of them to fail transaction on the evm. 

Compass: https://gnosisscan.io/address/0x8ab57eb10950564b9b24fdf5a7abd866fb2f64ce

![Image](https://github.com/VolumeFi/paloma/assets/19958639/b5a47791-5158-4e40-b7c3-b6b4142f9e52)

```
Jan 09 16:13:53 lcd-mainnet palomad[591855]: {"level":"info","module":"server","module":"x/palomaconsensus","message-id":319480,"queue-type-name":"evm/gnosis-main/evm-turnstone-message","chain-type":"evm","chain-reference-id":"gnosis-main","public-access-data":"0x3b94932711dfb3b7dfc0301b97d1cb2cc99a16af8bcf628fbb2d01d11b66ae10","time":"2024-01-09T16:13:53Z","message":"added message public access data"}
Jan 09 16:13:56 lcd-mainnet palomad[591855]: {"level":"info","module":"server","module":"x/palomaconsensus","message-id":319480,"queue-type-name":"evm/gnosis-main/evm-turnstone-message","chain-type":"evm","chain-reference-id":"gnosis-main","public-access-data":"0x7e1d9b3713883147dbe1280bfb23c347c928c64ed6d175e59a0da6b0f260b959","time":"2024-01-09T16:13:56Z","message":"added message public access data"}
```

**Full palomad log 2 minutes:** https://drive.google.com/file/d/1D-5sEFTcaYgz_gawxq73RKDBfIq0V8rB/view?usp=sharing

**Comment by byte-bandit** [comment]
Thank you for the log dump, that helped massively.

Turns out my initial assumption was correct, the message got reassigned while a Pigeon was actively handling it, so more than one Pigeon responded (with different data because the message got relayed twice effectively).

The current algorithm that handles setting message results does not take multi tenancy into account. I think the needed changes for that should be fairly trivial though, just take the first response we get, ignore any overrides and ensure that EITHER public access data OR error data is set. I can supply a fix for that.

@taariq @verabehr In the broader context, is a new challenge that arose with message reassignment. Messages are now delivered **at least** once, but possible more than once. I expect this can lead to problems with deterministic job execution. Building an **exactly once** delivery system is possible, but with some drawback:

a) it will be (sometimes much) slower, as we need to give Pigeons a proper chance to deliver, Pigeons will need to report back within a timeout window regardless of the outcome.
b) it can still fail in case a Pigeon doesn't play nice.

Most modern messaging solutions that are built with this **at least once** delivery are built with the patterns needed to ignore multiple messages sent. I **think** this should not be a problem for us, because compass checks each incoming message against its ID. But I wanted to throw it out here in case you guys can think of a scenario where sending the same message (with the same ID) more than once.

**Comment by byte-bandit** [comment]
Note to myself:

Something like this might happen:

> Msg 1 is assigned to Relayer A
> Relayer A picks up Msg1 but takes a long time
> Msg 1 is reassigned to Relayer B
> Relayer B picks up Msg1 and attempts to relay
> Relayer A fails to relay (i.e. `execution reverted`)
> Paloma sets error data, Pigeons attest
> Relayer B successfully relays, but is too late to call Paloma

This leaves the system in a corrupted state. The message will have been relayed, but Paloma assume it failed. It will retry sending the message using a new message ID. That will be relayed as well, compass will allow it, since it's two different message IDs (just the same payload).

So the same message will get executed twice. This is a potential attack vector and security risk. I need to take a closer look at how to ensure this doesn't happen.

**Comment by taariq** [comment]
>Most modern messaging solutions that are built with this at least once delivery are built with the patterns needed to ignore multiple messages sent. I think this should not be a problem for us, because compass checks each incoming message against its ID. But I wanted to throw it out here in case you guys can think of a scenario where sending the same message (with the same ID) more than once.

>This leaves the system in a corrupted state. The message will have been relayed, but Paloma assume it failed. It will retry sending the message using a new message ID. That will be relayed as well, compass will allow it, since it's two different message IDs (just the same payload).

@byte-bandit each target chain has its own block time. If a message isn't delivered within the block of the target chain that it was relayed to, then Paloma can assume it will not be delivered in that block. If Relay A picks up the message, and it's not delivered in the block it was assigned, then we can assume that the pigeon failed to relay. Thus, pigeons are only allowed a block for a message to "take a long time". Sometimes a block may take longer than 12 seconds. If that's the case, Paloma may need to wait before letting Relayer B take the message. Now, in the case that Relayer A fails to relay, execution is reverted, then Relayer B can't be successful. The payload will revert again since the first payload didn't change. So `Relayer B successfully relays, but is too late to call Paloma` is not a possible situation unless the payload changes.

**Comment by verabehr** [comment]
> Thus, pigeons are only allowed a block for a message to "take a long time".

would that include pending messages @taariq @byte-bandit?

**Comment by verabehr** [comment]
Will close this for now as we have the epic that we'll tackle at a later stage
