### ISSUE TITLE
BUG: Dune Analytics throwing an error: UNION query has different number of fields:

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1183]
Last updated 4 days ago.

The most recent execution, 1 hour ago, failed with the following error:

Error: Line 8:8: Failed analyzing stored view 'delta_prod.schema.query_3035919': line 5:6: Failed analyzing stored view 'delta_prod.schema.query_3054427': line 42:1: UNION query has different number of fields: 13, 14 at line 8, position 8 [Execution ID: 01HM56TPP26X1J0NWT02T18R7J].

Showing the most recent successful result from: 4 days ago

If you want these results to be fresher, you can always [refresh](https://dune.com/docs/query/query-executions#__tabbed_1_1) this dashboard or query, by clicking the Run button.

**Comment by fieldtheory123** [comment]
This is because the newest Curve TWAP contract (https://etherscan.io/address/0x8af32fbb0279b6713b628fe673ae5a5d15b6b3c6) has not had any tx so the query gets an empty result causing discrepancy with earlier contracts. I have commented out this contract temporarily so will put it back once there's tx. This should be resolved now.
