### ISSUE TITLE
HELP: Create Vesting Command with list of Paloma addresses

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1273]
Create vesting command and vesting json file with vesting accounts here: https://docs.google.com/spreadsheets/d/19tiA2O2rKO70jaRZIrd01O1CN2RzayQiDXqDQujh1FI/edit#gid=0

**Comment by byte-bandit** [comment]
[monthly-vest.py.zip](https://github.com/VolumeFi/paloma/files/14267574/monthly-vest.py.zip)

**Comment by byte-bandit** [comment]
Usage: `monthly-vest.py to-address grain-amount number-of-months`

Example: `monthly-vest.py paloma1r4kx8f02vat6lf7plr2nh83t5a4uwaqh123455 15000 12`

This will setup the JSON and command for a periodic vesting account paying out 1250grain per month into the given address for a total of 12 months.

The starting time for the vesting is fixed at 1 hour into the future when generating the JSON file.

If the total amount of tokens cannot be evenly distributed over the given amount of months, the monthly deposit is rounded down, with the last payment rounded up to fulfil the quota.

The full command needed is print at the end when running the command. Copy and paste to execute. Remove the `--dry-run` argument to actually execute.

I wasn't really able to test this due to obvious reasons, but hopefully it should be good.
