### ISSUE TITLE
Compass-EVM Upgrade for Pigeon Feed Phase 03

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1335]
Upgrade Compass-EVM for Pigeon Feed Phase 03 with the following upgrades discussed in: https://www.notion.so/volumefi/Pigeon-Feed-Compass-API-b7e7208291cc4f19ad851135c3fcd29a

**Comment by verabehr** [comment]
@byte-bandit will you confirm the requirements are up to date?

**Comment by byte-bandit** [comment]
@verabehr No, they're outdated. But I'm going to stake Steven's work and just apply the necessary changes myself to gain some speed. 

There still is some outstanding contract work that I won't be able to do though, which is getting market data from the liquidity pools and exchanging the necessary amount when relayers wish to cash out so that they're actually paid in GRAIN, not native coins.

It might be easier to pour that into a separate ticket for @webelf101 though.
