### ISSUE TITLE
ETH price prediction gaming bot Backend Script

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1444]
We need this backend script for ETH price prediction gaming bot.

Full requirements here.
https://www.notion.so/volumefi/EPIC-03-08-24-Juice-Bot-Price-Prediction-Competition-Sweepstakes-d014fa9bccca4715a9fb051bb9873371?pvs=4#c11312731b7e482db5a734f3111551f1

**Comment by verabehr** [comment]
@fullstack412  will you take a look at this backend script as well? https://github.com/VolumeFi/juice-bot-prediction/blob/main/index.js

**Comment by fullstack412** [comment]
@rootedbox You have to call the function `set_winner_list` and `set_active_epoch` from cosmwasm contract, not vyper contract. because those functions can be called by compass only.

So, the steps are below
 1, at 00:00 UTC everyday, Read `active_epoch_num` from the contract on ETH (active_epoch_num starts from 1)
 2, you can read the active epoch information by using `epoch_info['active_epoch_num']` from the ETH contract
 3, after that, read `epoch_info` from ARB contract and compare if that epoch_info.epoch_id is same as active_epoch_num
 4, if epoch_info.epoch_id < active_epoch_num, please call `set_active_epoch` function in CosmWasm contract. (when you call the `set_active_epoch`, please add these 4 fields in the struct {epoch_id: active_epoch_num, competition_start: epoch_info[active_epoch_num].competition_start, competition_end: epoch_info[active_epoch_num].competition_end, entry_cnt: 0}
 5, 24 hours later (00:00 UTC next day), read the `bid_info` from the ARB contract and calculate the winners, and call `set_winner_list` function in Cosmwasm contract, and loop 1~5 again per each 24 hours

**Comment by fullstack412** [comment]
cc @verabehr

**Comment by verabehr** [comment]
contracts: 
ETH : https://etherscan.io/address/0x196ff2c4d490e3c7a0d1cbe82d749a28611c5a0b
ARB: https://arbiscan.io/address/0x196ff2c4d490e3c7a0d1cbe82d749a28611c5a0b

**Comment by verabehr** [comment]
@rootedbox @fullstack412 FYI, I renamed the repo to be match the vyper contract and to be more descriptive. We'll have more prediction bots so we need to have the type of prediction in the name

**Comment by rootedbox** [comment]
@fullstack412 when I call set_active_epoch I'm getting the following.. any ideas?

```
Returned error: execution reverted: Not compass
    at Object.ErrorResponse (/home/rootedbox/app/eth-price-prediction-bot/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /home/rootedbox/app/eth-price-prediction-bot/node_modules/web3-core-requestmanager/src/index.js:170:36
    at request.onreadystatechange (/home/rootedbox/app/eth-price-prediction-bot/node_modules/web3-providers-http/src/index.js:111:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/rootedbox/app/eth-price-prediction-bot/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/rootedbox/app/eth-price-prediction-bot/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/rootedbox/app/eth-price-prediction-bot/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/rootedbox/app/eth-price-prediction-bot/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by fullstack412** [comment]
@rootedbox It's correct.
 - First, You can call `set_active_epoch` function once @taariq funded.
 - `set_active_epoch` function is only callable by Compass. You can't call this function directly.

**Comment by rootedbox** [comment]
@fullstack412 I've updated the scripts to use the cosm_wasm https://github.com/VolumeFi/eth-price-prediction-bot/pull/4 

however when I make the following call
```
 const bidInfoarr = await contractArb.methods
      .bid_info(epoch_id)
      .call();
```
I'm getting the following error. 


```
Error recording bids: Error: Returned error: execution reverted
    at Object.ErrorResponse (/home/rootedbox/app/eth-price-prediction-bot/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /home/rootedbox/app/eth-price-prediction-bot/node_modules/web3-core-requestmanager/src/index.js:170:36
    at request.onreadystatechange (/home/rootedbox/app/eth-price-prediction-bot/node_modules/web3-providers-http/src/index.js:111:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/rootedbox/app/eth-price-prediction-bot/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
```

**Comment by fullstack412** [comment]
fyi, `bid_info` will return the revert error when it has 0 length, so you can read `epoch_info`.`entry_cnt` first and only read `bid_info` when `epoch_info`.`entry_cnt`>0.

**Comment by fullstack412** [comment]
@rootedbox 
https://github.com/VolumeFi/eth-price-prediction-bot/blob/e5433f49f4106dcb348032424bdd655c70f387c6/index.js#L232
in this this, if the epoch_id is 0, then it means there is no epoch yet. 
epoch_id start from 1. so you need to check this value.


and also, i couldn't see any cron jobs in index.js, I think you need to use cron job for running these 2 functions below.
`set_winner_list` should be called only 1 time per 24 hours (at the end of the each epoch)
and `set_active_epoch` should be called only 1 time per 24 hours too (at the start of each epoch 00:00 UTC)

please read my previous comments in detail. thanks
https://github.com/VolumeFi/paloma/issues/1444#issuecomment-2084663447

cc: @verabehr @taariq

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/eth-price-prediction-bot/pull/5

I only set the winner list and fill in bid_info table once and thats when the epoch is over. set_active_epoch is only called when there is a new epoch which means if a new epoch is only once per 24 hours then it will only be set once per 24 hours.

cc: @fullstack412 @verabehr

**Comment by rootedbox** [comment]
service is now up and running waiting for funding / epochs to start cc: @verabehr @taariq @fullstack412

**Comment by fullstack412** [comment]
@rootedbox 
in codeline 74, you need to multiple 1000000 to the claimableAmount before you call the set_winner_list function because USDT decimal is 6.
and, claimable_amount type should be Number, should'nt be Float

**Comment by fullstack412** [comment]
@rootedbox 

New Eth price prediction 
ETH https://etherscan.io/address/0x92f99DDCc6a25CedE3F0400D201d4BE8266A7641
ARB https://arbiscan.io/address/0x92f99DDCc6a25CedE3F0400D201d4BE8266A7641

please update these lines below in https://github.com/VolumeFi/price-prediction/blob/main/index.js
code line 75, please remove 1000 * 1000000, because our daily reward amount isn't constant anymore. you can read daily prize amount from epoch_info.prize_amount
so like this, 
const claimableAmount = winners.length > 0 ? epochInfo.prize_amount / winners.length : 0;
for this, you need to get epochInfo object as parameter, not epochId

code line 114, please add one more line epoch_info.prize_amount into epoch
and code line 233, please add epoch_info.prize_amount for adding this value into database too
and you need to update contractABI.json and contractArbABI.json too to the latest one

cc: @taariq @verabehr
