### ISSUE TITLE
SUPPORT: What happened to the leverage bot for user 0x79c9a765d865f949c18335321436faafa865b2e6

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1471]
What happened the leverage bot on `0x79c9a765d865f949c18335321436faafa865b2e6`?

Bot creation tx: https://etherscan.io/tx/0x4eef2c5f77844b4151507ca4ff20cc8fd919ed8d29d5f8c99112fd0e2cfcf757

**Comment by wc117** [comment]
1. The user deposited ~15ETH for leverage with 5 times TWAP.
2. The first ~3 ETH was deposited.
3. Backend should have deposit remaining ETH to leverage but it didn't work.
4. He could repay bot the first ~3 ETH only. But other ETH got stuck in our Leverage bot.
5. In order to withdraw remaining ~12ETH, we must create the next bot for him. Otherwise no one can't touch the funds.
6. To withdraw the ETH, our Paloma chain must live and we should be able to send paloma message through the same Compass-EVM.
@taariq

**Comment by taariq** [comment]
@rootedbox why did the backend script fail on this TWAP?

**Comment by taariq** [comment]
We understand what happened. 12 ETH. TWAP failed and developer had no idea.
