### ISSUE TITLE
[BUG] Volume broke it's relays: eth-main - both gasPrice and (maxFeePerGas or maxPriorityFeePerGas) preventing relays.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1501]
Some validators that said that they updated are still getting the error message on eth-main that 1.11.1 was supposed to solve, but we see relays going through so this may be user error.

Tracking Sheet: https://docs.google.com/spreadsheets/d/1koiwSrmEScjmf7kpMTXFrN0P15ovVVs4vPH1LZgbDcc/edit?usp=sharing

**Comment by verabehr** [comment]
Updated the tracking sheet with ETH address, valoper address and whether they fail or relay. SECARD was able to deploy Compass EVM, but since fails. All failures except for 2 unrelated, but potentially related to the dupe message issue (see notes) are because of the error `both gasPrice and (maxFeePerGas or maxPriorityFeePerGas) specified` (0x626f746820676173507269636520616e6420286d6178466565506572476173206f72206d61785072696f726974794665655065724761732920737065636966696564)

Relaying is expected to continue to be slow, since we only have 2 pigeons who are actually relaying 
https://docs.google.com/spreadsheets/d/1koiwSrmEScjmf7kpMTXFrN0P15ovVVs4vPH1LZgbDcc/edit#gid=0

**Comment by verabehr** [comment]
I'm not sure how or if that would have an impact, but noting that only the 2 validators using liquify are relaying.

**Comment by taariq** [comment]
@byte-bandit we are unable to execute relays on `eth-main` and we are unable to restart Curve TWAPs.
1. All validators have upgraded to paloma v1.13.4
2. We have concensus on `eth-main` compass. 
3. Validators have confirmed they are `tx-type` I am closing https://github.com/VolumeFi/paloma/issues/1512 as it's not the solution to this issue. We have broken relays.

**Comment by taariq** [comment]
Users confirming they are type-2.

![Image](https://github.com/VolumeFi/paloma/assets/701864/6fb26be0-8d6b-43c4-8d43-7072de99823e)

**Comment by byte-bandit** [comment]
So, let's summarise what we know:

- The error **seems** to be coming from the `go-ethereum` framework (which we replace with the `op-geth` framework under the hood)
- At least two validators (`Volume` and `Liquify`) do not encounter this issue at all
- Most if not all other validators run into this issue.
- Having ensured that everyone is running on Pigeon `v1.11.1` and relayers having confirmed their configuration is setup correctly, it becomes more and more likely the error actually stems directly from the RPC
- We do not encounter this issue on other chains than `eth-main` at the moment, which again, makes an RPC error more likely than a framework error, since Pigeon doesn't distinguish between chains

I'm currently trying to verify this assumption by moving away from Liquify to another RPC provider to see if we encounter this issue as well. That will greatly help with the debugging. 

Unfortunately, Liquify currently seems to have some issues around their `BASE` endpoint, which prevents me from continuing here at the moment, as Pigeon needs to support EVERY chain. I've reached out to them.

---

## The way forward

- [ ] Reproduce the error by switching RPC providers
- [ ] Debug a relay and step through the code to verify transaction is actually built according to specs
- [ ] Investigate changes in `op-geth` and potentially upgrade our Pigeon, test using debug build on main validator

**Comment by taariq** [comment]
Relays are recovering.
