### ISSUE TITLE
CRV price prediction bot on arbitrum

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1559]
This very similar to the eth price prediction bot. 

Users predict the price of CRV on arbitrum, the bot that they start is the new LLamalend bot that is still in progress. 

Everything else is the same as for the eth price prediction bot

**Comment by fullstack412** [comment]
@verabehr what's the meaning of ethereum on title?

**Comment by verabehr** [comment]
Details on backend: https://github.com/VolumeFi/paloma/issues/1621

**Comment by fullstack412** [comment]
https://github.com/VolumeFi/price-prediction

This is the current price prediction backend script repository.
But Jason used non existed abi in the backend and copied and pasted the code from original one and updated the some smart contract interfaces only. and he closed the ticket without testing or confirming with me.
I was planning to flowing the backend script code with Jason step by step once we have llamalend bot as same as eth price prediction backend script case.
That's why I (or someone) need to work on this ticket.

@verabehr @taariq

**Comment by fullstack412** [comment]
I deployed the vyper and cosmwasm contract.
https://arbiscan.io/address/0xd63bFE61332312791b845ec90d363dE8003C9D46#code

i'm deploying the backend script now. 

cc: @verabehr
