### ISSUE TITLE
BUG: health no longer gets updated for curve-healthy-bot

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1627]
These 3 curve-healthy-bots have an outdated health value. There are no errors in the logs (there is really nothing in the logs). Screenshots below compare our value with the value queried from etherscan directly

Bot: 0xEC3c1940d88B8875b39b41e6D023026da500D4bB
![Image](https://github.com/VolumeFi/paloma/assets/19958639/3717c6da-cee0-40fd-a7ce-bc0dbf1a8a93)

Bot: 0x51bAeF85a9Ee3c6B6B96785344969b9f00d898b7
![Image](https://github.com/VolumeFi/paloma/assets/19958639/909a3a0d-dc17-4fb7-9580-262cd219e90f)

Bot: 0x88AF2874E5abB643C50F3F816a41778766d157b9

![Image](https://github.com/VolumeFi/paloma/assets/19958639/64451653-cfe0-45cb-8a98-b8d136d2d583)

**Comment by rootedbox** [comment]
For some reason CancelPendingBot is not part of the contract.. which causes an exception that causes the script not to do anything because it thinks it's currently processing. I've put in a fix for that but I'm not sure if need to add CancelPendingBot to the contract. I'm going to now take my name off of this ticket if you want to reassign to someone to add CancelPendingBot back to the contract. @verabehr

**Comment by verabehr** [comment]
Confirmed that this bug was resolved. It looks like the ABI wasn't updated on the server. I updated it, `CancelPendingBot` is in the ABI on the server now. @rootedbox is anything else required on your end, now that the event is there?
