### ISSUE TITLE
Confirm that mainnet pigeon is running correctly

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1774]
Mainnet pigeon keeps getting jailed with reason `No evidence supplied for contentious message {{message id}}` Public testnet validators are running fine with the same RPC endpoints. 

Also noticed that we're not getting any logs such as `got 0 messages from evm/eth-main/validators-balances` that indicate that pigeon is checking or receiving the items from the queues. Pigeon log level for mainnet validator is debug as it is for the public testnet validators

**Comment by byte-bandit** [comment]
I can see a couple of RPC related endpoint issues around `blast`. Did I understand correctly that the decision was to go back to quicknode for RPC? In that case we should probably relink our validator. Otherwise I've reached out to liquify to let them know.

**Comment by byte-bandit** [comment]
> Thanks @byte-bandit. Can the blast endpoint issues affect eth-main message checking? And no, we're not planning to go back to quicknode for the validators. We're only using it for the bots (and are trying to avoid even that)

Understood, we're staying with liquify for the validator. Still waiting to hear back from them, but the validator hasn't been jailed again, so maybe it's okay now. Haven't verified yet though. 

As to your question, yes, unfortunately with the current architecture, Pigeon needs 100% uptime across the board for all chain RPCs in order to start processing any messages.

**Comment by verabehr** [comment]
Got it, closing
