### ISSUE TITLE
Bug: Sync Transaction doesn't return raw_logs

### ISSUE THREAD

**Issue by wc117** [VolumeFi/paloma#197]
# Background

When we broadcast a transaction in sync mode, it returns the transaction hash but nothing more. According to the SyncTxBroadcastResult class definition, the raw_log should be returned. I confirmed that I couldn't get the raw log on broadcast and I couldn't get it when I tried to query the transaction data with hash just after running the broadcast_sync transaction function. But after some time I tried to query the transaction data again and I could all raw_log information. So it looks like the broadcast_sync function doesn't wait until the block is confirmed. I'd like to get the raw_log from SyncTxBroadcastResult class that returns from the broadcast_sync function.

**Comment by ToasterTheBrave** [comment]
@wc117 Would you please link me to the SyncTxBroadcastResult class definition you're referring to?  

Also, it looks like you have an example test case you've been running.  Would you be so kind as to provide those as well so I'm testing this exactly as you have been?

Final question for now.  This worked before?  What did the output look like previously?

**Comment by wc117** [comment]
https://github.com/VolumeFi/paloma.py/blob/main/paloma_sdk/core/broadcast.py#L21-L78

**Comment by ToasterTheBrave** [comment]
This was discussed in Discord, so I'll summarize here.  

This appears to be working as expected from the cosmos side.  This is a change in workflow because broadcast mode "Block" was removed.  This means that when broadcasting, the command will no longer wait for the transaction to be committed to a block, so there is no raw_log to return.

There was some confusion on the difference between sync and async broadcast modes.  These are mentioned in the documentation here: https://docs.cosmos.network/v0.47/run-node/txs#broadcasting-a-transaction.  Basically, neither sync nor async wait for the block creation.  

This responsibility is pushed down to the client.  The new expected workflow is to 
1. Broadcast the transaction
2. Wait for the transaction to be included in a block
3. Query the transaction to get the raw_log
