### ISSUE TITLE
[LIGTHTNODE] Review Security https://github.com/VolumeFi/lightnode-client/issues/11

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2145]
https://github.com/VolumeFi/lightnode-client/issues/11 anything we can do?

**Comment by maharifu** [comment]
@taariq gpg-agent will cache the key for the configured TTL, or until the session expires. Since we're running on docker, the session will always expire when the commands return (the container shuts down). So, for now, the concern is just on the `automate` command, which is long-lived. However, if we want `automate` to not nag the users for the passphrase, it has to be in memory somehow.

We could change the config to something like:
```
default-cache-ttl 7200 # 2 hours (in seconds)
max-cache-ttl 63072000 # 2 years (in seconds)
```
This would make the key stay cached as longs as it's used every 2 hours. This means it would expire after 2 hours if something went wrong and the process lingered without being used. I don't see a real need for this, but it's something we could easily add.

A better approach would be as Alessio suggested and use the in-memory store. This would keep the keys in memory on the same process, which could add some benefit. They would still be in-memory for the entire process duration, though. We would need to investigate how to persist the keys and load them into memory.

As for the other features (cloud-backup, key rotation, hardware wallet), they are nice-to-haves, but for advanced users. We could add them, but I'm not sure our current target would even use them.

**Comment by taariq** [comment]
Completed. Thanks!
