### ISSUE TITLE
[BUG] level=warning msg="Valset ID mismatch. Swallowing error to retry message..." chain-reference-id=base-main component=skyway-relay-batch

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2323]
[message(10).txt](https://github.com/user-attachments/files/17526190/message.10.txt)
1. it appears that we have problems on Base and Skyway batch "unable to estimate batches". 
2. Is this warning recoverable?
3. Attached Log from Steven that ran the tx.

time="2024-10-25T18:09:33Z" level=warning msg="Valset ID mismatch. Swallowing error to retry message..." chain-reference-id=base-main component=skyway-relay-batch skyway-batch-nonce=18 x-correlation-id=csdttlrajpmb8jetauj0
time="2024-10-25T18:09:33Z" level=error msg="unable to estimate batches" action=gas-estimate-skyway-batches batch-nonces="[18]" chain-reference-id=base-main error="processor::SkywayEstimateBatches: estimated 1 batches, but got 0"
time="2024-10-25T18:09:33Z" level=error msg="error returned in process loop" error="processor::SkywayEstimateBatches: estimated 1 batches, but got 0" x-correlation-id=csdttlrajpmb8jetauj0

**Comment by maharifu** [comment]
@taariq `Valset ID mismatch. Swallowing error to retry message...` happens when the valset ID on compass differs from the valset ID on paloma for that chain. This is recoverable and show go away after the next valset update. This most likely happened because pigeons failed to attest the valset update when they were crashing on Friday.

The skyway batches keep failing to estimate now anyway. We don't have much information on the error message, but they should be failing because the deployed ERC20 tokens are not registered in the current compass. They were deployed under a different compass. We need to deploy new ERC20 tokens first to overwrite these ones.

**Comment by taariq** [comment]
closing as fixed with the grains token deployment vote already underway
