### ISSUE TITLE
Update/add fee collection for palomabots

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#319]
### Background
https://www.notion.so/volumefi/EPIC-06-16-23-Palomabot-Fees-into-Paloma-Grain-Pool-0d40c46f180c4cb89e6ae6f715584b11?pvs=4

Fees collected from the paloma bots need cannot go directly into a paloma/volume controlled wallet, but should go into the Grain/token pools and swapped for GRAINs. Volume will return GRAINs to Paloma Foundation. 

### Done when

- [x] All bots fees are swapped for GRAINs and GRAINs are returned to the Paloma Foundation's GRAIN ERC20 contract. https://github.com/VolumeFi/paloma/issues/247

**Comment by taariq** [comment]
@wc117 did you have a chance to take a look at this?

**Comment by wc117** [comment]
`momentum bot pool collection is updated to be collected into the GRAIN/ETH or GRAIN/BNB pool instead of the refund wallet`

What does this mean exactly?

Can you describe how token flows and swaps? We will collect ETH or BNB in the bot contracts. What should I do with the fees for this story? @taariq

**Comment by taariq** [comment]
@wc117 thank for the follow-up. I have clarified the requirements here. Will you review? https://www.notion.so/volumefi/EPIC-06-16-23-Palomabot-Fees-into-Paloma-Grain-Pool-0d40c46f180c4cb89e6ae6f715584b11?pvs=4#021caa34f1d8481fa9574586fccc60c4

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/paloma/issues/247
