### ISSUE TITLE
Enforce Pigeon version in Paloma

### ISSUE THREAD

**Issue by ToasterTheBrave** [VolumeFi/paloma#462]
We need a way to ensure Pigeon is kept up to date.  Old versions of Pigeon may be incompatible with Paloma.

Let's implement this as part of the health check.  When Pigeon sends a health check, it should send some information about itself.  Paloma can then decide if Pigeon is correct and consider it unhealthy if any information is incorrect.  In this case specifically, we should send Pigeon's version.

**Comment by taariq** [comment]
To Build: However, we understand that jailing pigeons on the incorrect version will require that governance also be included for an upgrade of pigeon. Yes? We will need to have governance vote on the right Pigeon version so that there is consensus that can be checked. Thus, this feature will need governance integration.

**Comment by taariq** [comment]
This will also mean that we'll need a halt-height for pigeon upgrade proposals.
