### ISSUE TITLE
Re-enable Telegram Bot on Palomabot and Curvebot

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#501]
- [x] Revert the Telegram bot alert hiding from https://github.com/VolumeFi/palomabot/commit/5bbf169c8895f15e3cca844f3d221d7598ed5b8e
- [x] QA the Telegram bot alert functionality to ensure it works.
- [ ] Add telegram bot button to curvebot.fi

**Comment by taariq** [comment]
@rootedbox how can @jamie088 take over deploying the telegram bot functionality on the server from you?

**Comment by jamie088** [comment]
@rootedbox Could you please send me these env variables of bot info api?

PORT=
COINGECKO_API_KEY=
PG_USER=
PG_PASSWORD=
PG_HOST=
PG_DATABASE=
PG_PORT=
TELEGRAM_ID=
DB_LOCATION=

Because bot info api is working well on my local with my local data but it is not working on the server. So I'd like to check with the server data.

**Comment by verabehr** [comment]
@jamie088 - cc @rootedbox dm'd Jamie the variables found in `~/app/bot-info-api/.env`

**Comment by verabehr** [comment]
moving the last task to a separate ticket
