### ISSUE TITLE
BUG: My Curvebot bot does not show. 

### ISSUE THREAD

**Issue by fieldtheory123** [VolumeFi/paloma#511]
These are the deposit txes:
previous contract
https://etherscan.io/tx/0x6b27c11d1b747bd03241f3603a701fce7ba8df0ba093d48406337f36ab02a8c7

current contract
https://etherscan.io/tx/0xec4e25a55ea2230dceffe472120b20ce9d6bc4f01c830ee138765aff3001e4cc

Mybot page:
<img width="911" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/a10baf5f-db2c-4aac-bc74-777399773382">

**Comment by fieldtheory123** [comment]
@verabehr

**Comment by verabehr** [comment]
https://github.com/VolumeFi/curve-limit-order-bot-script/commit/5d89cd06086c8498989a60fe71a66aef00086f50
In Line 266, why did `token0` change into `token1`? If the update doesn't have some important meaning, we need to revert it.

https://github.com/VolumeFi/curve-limit-order-bot-script/blob/8ea8896287724ea099d7c13947d6b0f1cb813207/limit-orders.js#L278
I think this code line is the reason for the issue. We need to remove it because we don't input amount1 here.

**Comment by fieldtheory123** [comment]
Both LOB and stop-loss bots are not showing up for me again:

LOB deposit: https://etherscan.io/tx/0xea70fe8483ff9d750a6c0eb904c236e7118a2aa7b92a0fb317bad9f4f395e87c

Stop-loss deposit: https://etherscan.io/tx/0x9370beb492bdfaf27c5e2a8e76c9995b6439d2e252a98cb81be64f1c7ef41686
<img width="922" alt="image" src="https://github.com/VolumeFi/paloma/assets/18745242/b3de609b-97ba-4bb2-8fbe-c4186a7466b8">

**Comment by taariq** [comment]
Fixed. Closing.
