### ISSUE TITLE
BUG: Version 1.5.1 less than required v1.5.0 when running pigeon v1.5.1 from release.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#573]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

1. New pigeon release:
https://github.com/palomachain/pigeon/releases/tag/v1.5.1

2. Users download and build and then unjail.
Error: **pigeon is out of date.  Version 1.5.1 less than required v1.5.0** 
https://github.com/palomachain/paloma/blob/8b1dde09b1dfb43917f691bd554ade077b9e992c/app/app.go#L144

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

```
App version: 1.5.1
Build commit hash: ada161d3817cdced7aa3e9b98bb6ff37d4427933
```

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Pigeon version upgrade must not halt pigeon.

**Comment by byte-bandit** [comment]
This issue is connected to how our `semver` library interprets version numbers. I downloaded both `pigeon 1.5.0` and `pigeon 1.5.1` and ran them in private test net against `paloma 1.6.1` without any issues. 

The version output for `pigeon` reads: `v.1.5.x`

Our current implementation expects the version to be starting with `v`. It appears that building from source and not tagging appropriately will lead to a version without a leading `v`, i.e. simply `1.5.0`.

Without the leading v, our semver comparison interprets it as invalid and will always report as too low.

I am working on a fix, we can include it in the next planned Pigeon release.

**Comment by byte-bandit** [comment]
Also see: https://pkg.go.dev/golang.org/x/mod/semver#pkg-overview

> Package semver implements comparison of semantic version strings. In this package, semantic version strings must begin with a leading "v", as in "v1.0.0".

**Comment by taariq** [comment]
https://github.com/palomachain/pigeon/pull/228 fixed by @byte-bandit
