### ISSUE TITLE
BUG: CORS error for gecko.momentum api

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#591]
We're getting a CORS error from localhost and also here https://cors-test.codehappy.dev/?url=https%3A%2F%2Fgecko.momentumbots.palomachain.com&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=get

Attempted to fix by doing the following
`cd /etc/ngnix/sites-available`
`cp momentumbots.palomachain.com gecko.momentumbots.palomachain.com`
edit the domain inside the file
`sudo systemctl reload nginx`

But still same error

**Comment by rootedbox** [comment]
added 

add_header 'Access-Control-Allow-Origin' '*' always;
   add_header 'Access-Control-Allow-Credentials' 'true';
   add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,append,delete,entries,foreach,get,has,keys,set,values,Authorization' always;
   add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;

**Comment by rootedbox** [comment]
server {
  server_name momentum.palomabot.ai;

add_header 'Access-Control-Allow-Origin' '*' always;
   add_header 'Access-Control-Allow-Credentials' 'true';
   add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,append,delete,entries,foreach,get,has,keys,set,values,Authorization' always;
   add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;

  location / {
add_header 'Access-Control-Allow-Origin' '*' always;
   add_header 'Access-Control-Allow-Credentials' 'true';
   add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,append,delete,entries,foreach,get,has,keys,set,values,Authorization' always;
   add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;
   proxy_pass http://localhost:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

**Comment by rootedbox** [comment]
/etc/ngnix/sites-enabled
