### ISSUE TITLE
Update Paloma to only select validators that support all target chains as part of the valset

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#608]
As a validator supporting all paloma's target  chains, I want paloma to protect my investment by only selecting validators into the valset that support all the active paloma chains from governance.

**Acceptance Criteria**

- [x] 1. Upgrade from adding unjailed validators to the valset to validators that support all approved chains.
- [x] 2. (Added by Tyler) Create a new valset and force publish it when the chain resumes after a software update.
- [x] 3. Add test coverage and cut release.

**Comment by ToasterTheBrave** [comment]
I need some input for #2, just to make sure I understand the problem and how best to solve it.

First, I intend to publish a new valset to every chain after a successful update.  This seems pretty straightforward.

Publishing when a new chain is added is more involved.

When a new chain is added, we want to immediately publish a valset that excludes all validators that don't support that chain, right?

We can't do that right now because pigeons don't give chain info for inactive (in-proposal) chains.  When the chain goes live, we would have an empty valset.

This means that we need to know before the chain is published if the validators support it.  Pigeon needs to start reporting in for inactive chains, and paloma needs to start checking and storing info those chains.

Does this make sense?

**Comment by taariq** [comment]
Okay. I see. So, in order to create the valset when a new chain is added, we need to get chain-infos before the vote is passed. Okay, if we do not pursue this approach, is there a way to AVOID a stale valset when the chain is added, but not all pigeons in the current valset support the chain. I want to avoid another Compass-evm deployment failure. Are we able to do that?

**Comment by taariq** [comment]
Removed the post-vote valset chain-info support check. Let's get the initial win releaed and come back to the bigger problem of valset loss of 33% or more and how to preserve the chain in such a case.
