### ISSUE TITLE
BUG: Compass EVM failed to deploy on Ethreum Mainnet after upgrade proposal

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#755]
See EPIC for review from @verabehr 
https://www.notion.so/volumefi/EPIC-09-06-23-Notes-on-partially-failed-Compass-EVM-ETH-mainnet-deployment-24070dc3ee7f4240babfa9c2274f298b

**Comment by byte-bandit** [comment]
As discussed, compass failed to deploy due to missing funds on target chain (tx cost was `0.052 ETH`, but minimum on chain balance is only `0.05 ETH`, so it might not have been easy to find a validator with enough funds).

It then got stuck because the deployment wasn't removed, which is actually intended. We only remove it in case the deployment didn't end in an error.

After resetting, the contract deployed fine within seconds.
