### ISSUE TITLE
[BUG] "Incorrect Checkpoint" during SLC

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#802]
~When we do a "just in time" valset update, the valset update should happen after the submit logic call instead of before, so that we don't block the submit logic call execution.~ 

use the in-flight valset for message signing. That was Tyler's original plan after discovering that Paloma doesn't update the deployed valset until after it's been committed.

**Comment by byte-bandit** [comment]
This should work most of the time, but there are two culprits:

- the message will fail to be relayed in case the current valset is considerably different to the one stored on the target chain as it will fail to confirm consensus 
- the message might fail to be relayed during retries, as the valset update might have been forwarded in the meantime

**Comment by byte-bandit** [comment]
After looking at the code, I think we should keep the JIT valset update as it is, but use the in-flight valset for message signing. That was Tyler's original plan after discovering that Paloma doesn't update the deployed valset until after it's been committed.

**Comment by taariq** [comment]
From Tyler:

_The "fix" I was working on for the valset race condition doesn't work.  It actually just makes it worse.  Paloma doesn't mark a snapshot as published to a chain until after the block is committed and the pigeons attest to that.  I didn't think this was the case, but it is.  We don't currently have an easy way in Paloma of distinguishing if a valset is "publishing"

So... asking Paloma what the latest publish valset is ends up being out of date more often than asking the compass contract.  The code that's been committed to Paloma is fine because it just adds a query endpoint.  

The code I have for Pigeon just needs thrown away until more work is done in Paloma to expose that a valset is currently being published._

**Comment by taariq** [comment]
Another from Tyler and I think the solution:

_But this "Incorrect Checkpoint" is because the pigeons are signing it using the valset id as part of a salt.  The pigeons are using the previous valset when the just-in-time valset happens immediately before the submit logic call.

The fix for this is to use the in-flight valset id.  My attempts to push that out before leaving failed though 
I'm really surprised we had a new valset so quickly though.  Must still be a good bit of jailing going on_

**Comment by byte-bandit** [comment]
Input from Tyler after further inquiry:

---

Sorry for the slow reply.  It's still confusing to me, so I could be partially wrong, but if I remember right, Paloma is generating the bytes to sign and passing it as part of the message. Pigeons then just sign that with their key.

Compass deconstructs the signed data to confirm it looks as expected from each pigeon.

I believe (if memory serves me right) the bytesToSign that Paloma generates for the message has the current valset ID as part of the generated bytes.  Compass then deconstructs using the current valset ID that it has as well.

So... If Paloma builds the bytes using valset ID 4, and at the same time submits a job for valset ID 5 to be created...
Pigeons will all sign bytes including valset 4, but compass ends up trying to deconstruct using the new valset ID of 5 because that valset update went through too...  The bytes don't match.

Hope this helps, and please remember that Paloma code is very confusing and it's possible I'm misunderstanding it as well.

Cheers!
Tyler

**Comment by byte-bandit** [comment]
I will need to check if this is actually the case and what can be done about it.

**Comment by byte-bandit** [comment]
After looking at the code a lot more, I believe Tyler might have misremembered some of this. I found no evidence of the valset ID being used in any part of message signing, neither as part of bytesToSign, nor of the actual signature itself, nor the salt. The bytes to sign in the gravity bridge are fairly complex, but even there, I only found usages of nonces, nothing related to the valset at all.

Next, I looked at the code that actually emits the error we're seeing [here](https://github.com/palomachain/compass-evm/blob/6776efbbddbe3c301c18e6606ac253a23017dee1/contracts/Compass.vy#L148). It's basically comparing the last stored valset against the one that was sent with the logic call. The consensus is built using [this logic]( https://github.com/palomachain/compass-evm/blob/6776efbbddbe3c301c18e6606ac253a23017dee1/contracts/Compass.vy#L124). You can see, the message signature is not even considered here. We're building the consensus snapshot using:

- the validators
- their powers
- the valset ID
- (and some static information that doesn't change)

I'd say it's safe to say that this error is simply a symptom of the logic call coming in before the valset update has been processed - and since those are not being retried (yet), the call fails entirely.

With `v1.9.0`, message calls should be retried. Meaning they should catch up with the valset update and be processed successfully eventually.

**Comment by byte-bandit** [comment]
Getting back to this, yes, Pigeon will query for the compass EVM error and attach it to the message as error data. This won't be retried (yet), but we did talk about the concept of having SLC messages being retried `n` times before completely removing them.

**Comment by taariq** [comment]
Okay. So to reflect: We do NOT have retries on SLCs. Yes?

So, we'll need a new ticket for SLC retries?

**Comment by byte-bandit** [comment]
> Okay. So to reflect: We do NOT have retries on SLCs. Yes?
> 
> So, we'll need a new ticket for SLC retries?

It depends at what stage the call actually fails.

1.) In case the message was not even attempted to be relayed, i.e. due to Pigeon not able to confirm consensus, the relay attempt should be retried. This was not the case up until recently, and no failure was being recorded, so the message just got "stuck". That is now fixed and will be in `v1.9.0`.

2.) In case calling the contract goes wrong. This might be related to numerous reasons: missing funds, network problems, or an error returned from the compass contract itself (for whatever reason). Usually, a Pigeon that's not able to relay would not be in the active valset, but sometimes this changes too quickly or just after the Pigeon was selected. This case is different, in a sense that an attempt was actually made - and failed. The failure is recorded on the message, and the message removed from the queue. 

My pitch is for number 2. I feel like the system would become a bit more reliable if messages that were actually attempted to be relayed would be assigned to a new pigeon and the delivery re-attempted (i.e. 3 times total). It might still fail due to a compass error, but it would help with RPC endpoint issues or missing funds.

**Comment by verabehr** [comment]
thanks @byte-bandit how much effort would a retry be (one retry only)?

**Comment by byte-bandit** [comment]
@verabehr Hard to say. Maybe a day or two. The retry logic of messages is currently a bit all over the place, sometimes triggered by Paloma, sometimes by Pigeons.

The way I'd solve this is by hooking into the code that removes a message from the queue, copy the contents and put a new message on the queue with the same parameters. However, I think we only want this for SLC calls at the moment, as compass deployments and valset updates will both eventually be retried implicitly by other components.

I'll see if I can get it into the 1.9.0 release, but since I have to cut the release tonight, it'll be a tight fit.
