### ISSUE TITLE
[Gravity] Pigeon & Paloma support for Compass EVM update

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#875]
This is the pigeon side for the work started here https://github.com/VolumeFi/paloma/issues/795

### Done when

- [ ] pigeon actually calls the appropriate method on old compass
- [ ] paloma verifies TX has not yet been executed again

**Comment by byte-bandit** [comment]
@wc117 

Can you confirm my understanding of what needs to happen in order to support this? 

1. Upload a new version of compass
2. Prepare a submit local call message to call `new_compass` on the ERC20 token address.
3. Send this SLC transaction to the **old compass** address
4. Old compass will then relay the logic call to the ERC20 token, where `new_compass` will be executed.

**Comment by wc117** [comment]
@byte-bandit 
This is what we need.
1. Upload a new version of compass
2. Deploy a new compass
3. Send a SLC transaction(that includes new compass address) to the old compass to update ERC20 token configuration.

**Comment by wc117** [comment]
No. It is the issue. We should call `old_compass` with `new_compass` address. The new compass address can get only after deploying new compass. So we need a feature to call `old_compass` after existing `new_compass`.

**Comment by byte-bandit** [comment]
@wc117 Can you be more specific what you mean by this?

Pigeon is able to make calls to the **old** compass AFTER the **new** compass has been deployed, that should not be a problem. But I don't know exactly what to call?

Like, is there a method on the compass contract directly I can call? Because I didn't see it. I THINK I need to make a call to the old compass with a `logic_call` transaction, that contains the ERC20 token contract address and the bytecode to execute the `new_compass` method which is defined by the token contract.

Is that correct?

**Comment by byte-bandit** [comment]
@verabehr Most likely both to be honest.

**Comment by wc117** [comment]
@byte-bandit Yes, you are correct.
