### ISSUE TITLE
Pigeons should remove gravity batch after execution

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#895]
Pigeons are supposed to remove a batch once its been executed, and this doesn't seem to work yet either. I assume we have to supply the same fix I did for this at another point in the code.

related to https://github.com/VolumeFi/paloma/issues/880

**Comment by byte-bandit** [comment]
I believe this is caused by missing interface registrations that were likely simply forgotten when implementing the gravity changes. It's the same thing that happened to me with the `AddStatusUpdate` message. 

It's interesting that missing interface registrations sometimes work and sometimes don't, and I have no idea why. I have installed a dev build on bird lady. If my fix proves to be correct, we can distribute it among validators and it should solve the issue.
